blogproject/blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'  # 视图函数命名空间
urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^myapi$', views.my_api, name='myapi'),
    url(r'^mypost$', views.PostAPIView.as_view(), name='mypost'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detailView.as_view(), name='detail'),
    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),

    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.archivesView.as_view(), name='archives'),

    url(r'^category/(?P<pk>[0-9]+)/$',
        views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',
        views.TagView.as_view(), name='tag'),
    # url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
]
# def brinySearch(arr,target):
#     l=0
#     r=arr.length-1
#     while l<=r:
#         mid = (l+r)/2
#         if arr[mid] == target:
#             return mid
#         if arr[mid] < target:
#             l = mid+1
#         else:
#             r = mid-1
#     return -1

blogproject/blogproject/urls.py
from django.contrib import admin
# from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('blog.urls')),
    path(r'', include('comments.urls'))
]

blogproject/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'

urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',
        views.post_comment, name="comment")
]

blogproject/blog/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import User
from six import python_2_unicode_compatible
from django.urls import reverse
import markdown
from django.utils.html import strip_tags
# Create your models here.


@python_2_unicode_compatible
class Category(models.Model):
    '''
     Django 要求模型必须继承 models.Model 类。
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了分类名 name 的数据类型，CharField 是字符型，
    CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
    Django 内置的全部类型可查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    '''
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=50)
    # name = models.CharField(_(""), max_length=50)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """
    # 文章标题
    title = models.CharField(max_length=70)
    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time', 'title']

    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    body = models.TextField()

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True)

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(User, on_delete=models.CASCADE)

blogproject/comments/models.py
from django.db import models
from six import python_2_unicode_compatible
# Create your models here.

# python_2_unicode_compatible 装饰器用于兼容 Python2


@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateField(auto_now_add=True)

    post = models.ForeignKey("blog.Post", on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

blogproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category, Tag
from .serializers import PostSerializer
from rest_framework.generics import ListCreateAPIView
import markdown
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
from django.db.models import Q
# Create your views here.

import json
 
# Create your views here.
from django.views.decorators.csrf import csrf_exempt

class PostAPIView(ListCreateAPIView):
    serializer_class = PostSerializer
    queryset = Post.objects.all()




@csrf_exempt
def my_api(request):
    ret = []
    if request.method == 'GET':
        post_list = Post.objects.all().order_by('-created_time')
        for obj in post_list:
            ret.append({
                "title":obj.title,
                "author":"%s"%obj.author,
                "views":"%s"%obj.views,
                "name":"%s"%obj.category.name,
            })
        return HttpResponse(ret)
    else:
        dic['message'] = '方法错误'
        return HttpResponse(json.dumps(ret, ensure_ascii=False))


def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(
        request, 'blog/index.html', context={'post_list': post_list}
    )


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 阅读量 +1
    post.increase_views()
    post.body = markdown.markdown(post.body, extensions=['markdown.extensions.extra',
                                                         'markdown.extensions.codehilite',
                                                         'markdown.extensions.toc', ])

    # 记得在顶部导入 CommentForm
    form = CommentForm()
    # 获取这篇 post 下的全部评论
    comment_list = post.comment_set.all()
    # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
    context = {"post": post,
               "form": form,
               "comment_list": comment_list
               }
    return render(request, 'blog/detail.html', context=context)


def archives(request, year, month):
    post_list = Post.objects.filter(
        created_time__year=year, created_time__month=month).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'blog/index.html', {'error_msg': error_msg})
    post_list = Post.objects.filter(
        Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg, 'post_list': post_list})


#  基于类的通用视图：ListView 和 DetailView 中的内容

class IndexView(ListView):

    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 3


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=cate)


class archivesView(IndexView):
    def get_queryset(self):
        return super(archivesView, self).get_queryset().filter(created_time__year=self.kwargs.get('year'), created_time__month=self.kwargs.get('month'))


class detailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(detailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(detailView, self).get_object(queryset=None)
        post_body = markdown.markdown(post.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(detailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            "form": form,
            "comment_list": comment_list
        })
        return context

blogproject/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
<article class="post post-{{post.pk}}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                                datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">4 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                {{post.body|safe}}
            </div>
        </article>
        <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                   <form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4">
                        <label for="{{ form.name.id_for_label }}">名字：</label>
                        {{ form.name }}
                        {{ form.name.errors }}
                        </div>
                        <div class="col-md-4">
                        <label for="{{ form.email.id_for_label }}">邮箱：</label>
                        {{ form.email }}
                        {{ form.email.errors }}
                        </div>
                        <div class="col-md-4">
                        <label for="{{ form.url.id_for_label }}">URL：</label>
                        {{ form.url }}
                        {{ form.url.errors }}
                        </div>
                        <div class="col-md-12">
                        <label for="{{ form.text.id_for_label }}">评论：</label>
                        {{ form.text }}
                        {{ form.text.errors }}
                        <button type="submit" class="comment-btn">发表</button>
                        </div>
                    </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{post.comment_set.count}}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date">{{ comment.created_time }}</time>
                                <div class="text">
                                {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
    <ul>
        {% for tag in post.tags.all %}
            <li>
                <a href="#">{{ tag.name }}</a>
            </li>
        {% endfor %}
        </ul>
{% endblock toc %}

blogproject/templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    
    {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                                datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">4 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{post.get_absolute_url}}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>

        

    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}

    {% if is_paginated %}
    <div class="pagination">
        <ul>
    <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
        {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
        {% endif %}
        <!-- 显示当前页面信息 -->
        <li class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</li>
        <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">下一页</a></li>
        {% endif %}
        </ul>
        </div>

    {% endif %}
{% endblock main %}
{% block toc %}
                
{% endblock toc %}